### ISSUE TITLE
Why not #[repr(x)]` instead of #[EnumReprType = "x"]?

### ISSUE THREAD

**Issue by faern** [dmnsafonov/enum-repr#4]
Hi. I find this library is really on to something and fills an important role. However, I'm a bit afraid of the suppressed warnings when it's casting between types that's outlined in the limitations section of the documentation. To my understanding the generated code has to do all this casting because it's never aware of the actual memory representation of the enum.

Is it a conscious design decision to make this library work on enums without the [`#[repr(x)]`](https://doc.rust-lang.org/nomicon/other-reprs.html#repru-repri) attribute and to ignore it for those where it exists? If not, I believe parsing that attribute instead of a custom one would be able to greatly simplify the code in the sense that the integer type it's converting to and from would always be the same as the one backing the enum, severely limiting the amount of casting needed and the risk of something being truncated.

If this is something you want this library to to, I would gladly help in contributing the code that can do this :) Cheers.

**Comment by dmnsafonov** [comment]
I mostly intended to use it to wrap libc constants, so it did not contain any checking of the kind.

Now, I made it generate compiler warnings errors on that "limitations" case in e275bf7a40bf35a68661a56c75fb74d5ff629f36.  But, as a derive macro cannot change the enum definition, an explicit cast of constants to isize or another ```#repr(...)``` is needed anyway.  The best I can think of is stripping "as isize" from the constants and making an error in dead generated code as I implemented it.  That creates code like ```CONST as REPR_TY as isize``` if the const type and the repr type are different.

**Comment by faern** [comment]
The fact that an enum without `#[repr(x)]` is being backed by an `isize` is not stabilized in the ABI I think, and could theoretically change at any point in time.

Yes, that this crate can use type aliases like `c_int` is definitely nice. I also use this type of thing solely to wrap C constants when I'm doing FFI. But I manually follow the aliases and define them as `#[repr(i32)]` and similar. Which obviously won't work of aliases that point to different types on different platforms sadly.

It would be nice if conversion to and from the repr could be done without the repr actually being assigned to the enum variant. So the enum is more of a "pure" Rust enum, and the conversion happens cleanly on the side so to speak. But I guess that is not really possible to do as a proc macro. Except if all values associated with variants were taken in separately like:
```rust
#[derive(EnumRepr)]
#[EnumRepr = "Ipv4=IPPROTO_IP, Ipv6=IPPROTO_IPV6"]
pub enum MyCConsts {
    Ipv4,
    Ipv6,
}
```
Which would be a bit terrible also...

**Comment by dmnsafonov** [comment]
Thanks for your comment!  With 0ec37bdd1a547a75778427ec355ce52a3902ba86 it should not break, as I forced the `#[repr(isize)]`.

Now it works like
```
#[EnumRepr(type = "c_int")]
pub enum IpProto {
    IP = IPPROTO_IP,
    IPv6 = IPPROTO_IPV6,
    // …
}
```

Also, I will make it use `#[repr(type)]` if type is of a builtin type when I get to it soon.
